### ISSUE TITLE
Error connecting new BBMRI endpoint

### ISSUE THREAD

**Issue by vabishaa** [ejp-rd-vp/vp-dp-backend#48]
**Describe your problem.**

Error while using the new L2 endpoint "https://collection-discovery.bbmri-eric.eu:5050/api/catalogs"
Note: Endpoint will be removed and deployed on the productive system for now

**If it is a bug name steps to reproduce**

Steps to reproduce the behavior: Start application with according endpoint and see following error message

[ae52daab, L:/192.168.178.60:59340 - R:collection-discovery.bbmri-eric.eu/78.128.247.220:5050] The connection observed an error

javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:130) ~[na:na]
        .....

**Comment by HaddadTala** [comment]
@svituz FYI

**Comment by svituz** [comment]
Hi, I'm working on that.

**Comment by vabishaa** [comment]
@HaddadTala @svituz It works now and is updated in the productive system. Thanks for the quick fix!
