### ISSUE TITLE
orphadata logo

### ISSUE THREAD

**Issue by Orphanet** [ejp-rd-vp/vp-dp-backend#51]
**Describe your problem.**
Wrong logo for orphadata is displayed on resources list

in vp-dp-backend/src/main/resources/static/resources.txt
Orphadata section
"logo": "https://eurogen-ern.eu/wp-content/uploads/2016/11/eUROGEN-Website-Logo.jpg",
shoud be :
"logo": "https://www.orphadata.com/wp-content/uploads/2022/04/logo-orphadata-transp-white-e1649945229786.png",

Plus :
 "id": "20",
 which is the same than :
 "Duchenne Parent Project" (  "id": "20" )

Thanks !

**Comment by vabishaa** [comment]
no longer relevant due to VP Index integration
